import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Upload, FileText, Download } from 'lucide-react';
import html2pdf from 'html2pdf.js';
import { notesAPI } from '../services/notes.api';

const Notes = () => {
  const [uploadedFile, setUploadedFile] = useState(null);
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(false);

  const handleFileUpload = async (e) => {
    const file = e.target.files[0];
    if (file) {
      setUploadedFile(file);
      setLoading(true);
      try {
        // Call the backend API to upload and process the file
        const response = await notesAPI.uploadDocument(file);
        setSummary(response.summary); // Extract the summary object from response
      } catch (error) {
        console.error('Error uploading file:', error);
        // Fallback to mock data if API fails
        setSummary({
          title: 'AI-Generated Summary',
          content: 'This is a summarized version of the uploaded document. The AI has analyzed the content and extracted key points, main ideas, and important concepts for quick review.',
          keyPoints: [
            'Main concept 1: Understanding the fundamentals',
            'Main concept 2: Advanced applications',
            'Main concept 3: Practical implementation'
          ]
        });
      } finally {
        setLoading(false);
      }
    }
  };

  const handleDownloadPDF = () => {
    if (!summary) return;

    const element = document.createElement('div');
    element.innerHTML = `
      <div style="font-family: Arial, sans-serif; padding: 20px; max-width: 600px; margin: 0 auto;">
        <h1 style="color: #1f2937; margin-bottom: 20px;">${summary.title}</h1>
        <p style="color: #4b5563; line-height: 1.6; margin-bottom: 20px;">${summary.content}</p>
        <h2 style="color: #1f2937; margin-bottom: 15px;">Key Points:</h2>
        <ul style="color: #4b5563;">
          ${summary.keyPoints.map(point => `<li style="margin-bottom: 8px;">${point}</li>`).join('')}
        </ul>
        <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 12px;">
          Generated by CampusIQ Smart Notes
        </div>
      </div>
    `;

    const opt = {
      margin: 1,
      filename: 'campusIQ-notes.pdf',
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
    };

    html2pdf().set(opt).from(element).save();
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-900 via-purple-900 to-blue-900 p-4">
      <div className="max-w-4xl mx-auto">
        <motion.h1
          className="text-4xl font-bold text-white text-center mb-12"
          initial={{ opacity: 0, y: -50 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          Smart Notes
        </motion.h1>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Upload Section */}
          <motion.div
            className="bg-white/10 backdrop-blur-xl rounded-2xl p-8 border border-white/20"
            initial={{ opacity: 0, x: -50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5 }}
          >
            <h2 className="text-2xl font-semibold text-white mb-6">Upload Document</h2>
            <div className="border-2 border-dashed border-white/30 rounded-lg p-8 text-center">
              <Upload className="mx-auto text-white/50 mb-4" size={48} />
              <p className="text-white/70 mb-4">
                Drag and drop your PDF or text file here, or click to browse
              </p>
              <input
                type="file"
                accept=".pdf,.txt,.doc,.docx"
                onChange={handleFileUpload}
                className="hidden"
                id="file-upload"
              />
              <label
                htmlFor="file-upload"
                className="bg-gradient-to-r from-blue-500 to-purple-600 hover:from-blue-600 hover:to-purple-700 text-white px-6 py-3 rounded-lg font-semibold cursor-pointer transition-all duration-300 inline-block"
              >
                Choose File
              </label>
            </div>
            {uploadedFile && (
              <div className="mt-4 p-4 bg-white/10 rounded-lg">
                <div className="flex items-center gap-3">
                  <FileText className="text-blue-400" size={20} />
                  <span className="text-white">{uploadedFile.name}</span>
                </div>
              </div>
            )}
          </motion.div>

          {/* Summary Section */}
          <motion.div
            className="bg-white/10 backdrop-blur-xl rounded-2xl p-8 border border-white/20"
            initial={{ opacity: 0, x: 50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
          >
            <h2 className="text-2xl font-semibold text-white mb-6">AI Summary</h2>
            {loading ? (
              <div className="flex items-center justify-center h-64">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-white"></div>
              </div>
            ) : summary ? (
              <div className="space-y-4">
                <h3 className="text-xl font-medium text-white">{summary.title}</h3>
                <p className="text-white/80 leading-relaxed">{summary.content}</p>
                <div>
                  <h4 className="text-lg font-medium text-white mb-3">Key Points:</h4>
                  <ul className="space-y-2">
                    {summary.keyPoints.map((point, index) => (
                      <li key={index} className="flex items-start gap-2">
                        <div className="w-2 h-2 bg-blue-400 rounded-full mt-2 flex-shrink-0"></div>
                        <span className="text-white/80">{point}</span>
                      </li>
                    ))}
                  </ul>
                </div>
                <button 
                  onClick={handleDownloadPDF}
                  className="flex items-center gap-2 bg-gradient-to-r from-green-500 to-green-600 hover:from-green-600 hover:to-green-700 text-white px-4 py-2 rounded-lg font-semibold transition-all duration-300 mt-6"
                >
                  <Download size={16} />
                  Download as PDF
                </button>
              </div>
            ) : (
              <div className="flex items-center justify-center h-64 text-white/50">
                <div className="text-center">
                  <FileText size={48} className="mx-auto mb-4" />
                  <p>Upload a document to see AI-generated summary</p>
                </div>
              </div>
            )}
          </motion.div>
        </div>
      </div>
    </div>
  );
};

export default Notes;